### PR TITLE
removed all printing of duplicate atom classes/types in bonded or non-bonded parameters in the FF file

### PR DESCRIPTION
**Pull request by bc118**
The printing of duplicate atom classes/types in bonded or non-bonded parameters could cause some issues.  This covers mass, non-bonded, bonds, angles, dihedrals, and impropers.  

1. If the simulation engines don't catch them, they may cause issues or errors, so we added some checks to stop double printing.
2. If the values for the same classes/types combinations (or same by rearranging order properly) are different, an error is now raised.  This creates a more readable file and also prevents the same or multiple combined force fields from just selecting one or more bonded or non-bonded parameters via the simulation engine allows it.

### CODE REVIEW

**Comment by LSchwiebert** [comment]
I think in point 2, you left out "are different" after the parentheses. (Just mentioning it in case someone looks at this in the future.) Anyway, the patch looks good to me.

**Review by LSchwiebert — APPROVED** [review]
These changes all look good and address the issue.

**Comment by bc118** [comment]
Note the CodeCov test % coverage is due to "catch" all cases in bonded/non-bonded comparison.  I am not sure how to generate these automatically through the system, but they are these it does every happen.

**Comment by LSchwiebert** [comment]
You would need to create test cases that take that branch -- ones with an error in this case. I think it's OK to approve without this coverage, as these are error handling segments. None of the passing cases are triggering them.

**Pull request merged**
