### PR TITLE
sympy.simplify changed to symengine.sympify

### PR DESCRIPTION
**Pull request by bc118**
changed environment packages, docs updated to Python 3.9 and 3.10, and sympy.simplify changed to symengine.sympify to speed up the calcs.

### CODE REVIEW

**Comment by bc118** [comment]
@daico007 

looks like something in pydantic is breaking here.  Likely in mosdef.  Can you check this out?

**Comment by daico007** [comment]
I think I can pin the pydantic version on gmso feedstock to get by for now. I've already raised an issue on gmso github, hopefully we can get the fix in the next few days.

**Comment by daico007** [comment]
https://github.com/conda-forge/gmso-feedstock/pull/17 pydantic version pinned, I will probably try to push a dummy commit in a minute to restart the tests.

**Review by daico007 — APPROVED** [review]
LGTM!

**Pull request merged**
